export const productPromptJSON = [
    {
      name: 'adidas Samba OG',
      description: 'Classic Adidas Samba OG with timeless style and comfort. Leather upper, suede overlays.',
      color: 'Black/White',
      category: 'Men',
      tags: ['retro', 'casual', 'indoor', 'classic', 'lifestyle', 'leather', 'minimal', 'iconic'],
      sportType: ['indoor'],
      slug: '/products/1',
    },
    {
      name: 'Converse Chuck 70 Low',
      description: 'Classic silhouette with modern updates. Premium materials and enhanced cushioning.',
      color: 'White',
      category: 'Unisex',
      tags: ['canvas', 'casual', 'minimal', 'street', 'iconic', 'low-top', 'everyday'],
      sportType: [],
      slug: '/products/2',
    },
    {
      name: 'Veja Campo Chromefree Leather',
      description: 'Sustainable and stylish. Chromefree leather and organic materials.',
      color: 'White/Olive',
      category: 'Unisex',
      tags: ['eco', 'minimal', 'casual', 'sustainable', 'clean look', 'organic'],
      sportType: [],
      slug: '/products/3',
    },
    {
      name: 'New Balance 550',
      description: 'Revival of a basketball classic with clean leather construction.',
      color: 'Navy',
      category: 'Men',
      tags: ['retro', 'basketball', 'leather', 'vintage', 'street'],
      sportType: ['basketball'],
      slug: '/products/4',
    },
    {
      name: 'Nike Dunk Low',
      description: 'Classic basketball style with premium suede and leather in modern brown tones.',
      color: 'Brown',
      category: 'Men',
      tags: ['casual', 'basketball', 'suede', 'street', 'low-top'],
      sportType: ['basketball'],
      slug: '/products/5',
    },
    {
      name: 'UGG M Classic Ultra Mini',
      description: 'Lower shaft height, cozy suede and sheepskin build.',
      color: 'Chestnut',
      category: 'Unisex',
      tags: ['winter', 'cozy', 'indoor', 'warm', 'home', 'casual', 'relax', 'comfortable'],
      sportType: [],
      slug: '/products/6',
    },
    {
      name: 'Nike Air Jordan 1 Low SE "Gold"',
      description: 'Luxurious flair with rich gold overlays and timeless branding.',
      color: 'Gold',
      category: 'Men',
      tags: ['jordan', 'luxury', 'showy', 'gold', 'statement', 'low-top', 'streetwear'],
      sportType: [],
      slug: '/products/7',
    },
    {
      name: 'Nike Air Jordan 1 Retro High OG Brotherhood',
      description: 'High performance basketball shoes in vibrant yellow.',
      color: 'Yellow',
      category: 'Women',
      tags: ['high-top', 'performance', 'court', 'basketball', 'vibrant'],
      sportType: ['basketball'],
      slug: '/products/8',
    },
    {
      name: 'Nike Air Jordan 1 Mid SE Purple',
      description: 'Limited edition purple Air Jordan 1 Mid. Stylish and comfortable.',
      color: 'Purple',
      category: 'Women',
      tags: ['jordan', 'showy', 'stylish', 'limited edition', 'mid-top'],
      sportType: [],
      slug: '/products/9',
    },
    {
      name: 'Nike Air Jordan 1 Low Tie Dye',
      description: 'Low-cut, colorful and bold. For statement makers.',
      color: 'Tie-Dye',
      category: 'Men',
      tags: ['colorful', 'low-top', 'bold', 'creative', 'fun', 'vibrant'],
      sportType: [],
      slug: '/products/10',
    },
    {
      name: 'Converse Chuck Taylor All Star 70 Hi Comme des Garçons PLAY Black',
      description: 'Iconic Converse 70 Hi reimagined by CDG PLAY. Street-style edge.',
      color: 'Black',
      category: 'Women',
      tags: ['cdg', 'black', 'street', 'fashion collab', 'high-top', 'iconic'],
      sportType: [],
      slug: '/products/11',
    },
    {
      name: 'Converse Chuck Taylor All Star 70 Hi Comme des Garçons PLAY Blue',
      description: 'Playful twist with blue colorway and iconic CDG heart logo.',
      color: 'Blue',
      category: 'Women',
      tags: ['cdg', 'blue', 'street', 'fashion collab', 'high-top', 'fun'],
      sportType: [],
      slug: '/products/12',
    },
    {
      name: 'Nike Air Jordan 1 Mid Lakers 2022',
      description: 'Lakers-inspired AJ1 Mid in striking purple and gold.',
      color: 'Purple/Gold',
      category: 'Unisex',
      tags: ['jordan', 'lakers', 'basketball', 'mid-top', 'purple', 'gold', 'limited edition'],
      sportType: ['basketball'],
      slug: '/products/13',
    },
    {
      name: 'Nike Air Jordan 1 High Element Gore-Tex Light Curry',
      description: 'Rain-ready Gore-Tex infused high-top with streetwear style.',
      color: 'Light Curry',
      category: 'Women',
      tags: ['winter', 'waterproof', 'high-top', 'streetwear', 'rainy day', 'gore-tex'],
      sportType: [],
      slug: '/products/14',
    },
    {
      name: 'adidas Spezial Handball',
      description: 'Handball classic from 1979, modernized for lifestyle use.',
      color: 'Brown',
      category: 'Men',
      tags: ['retro', 'casual', 'handball', 'indoor', 'classic'],
      sportType: ['handball'],
      slug: '/products/15',
    }
  ];
  